version: '3.8'
services:

  frontend:
    image: ibonish/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/


  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../backend/foodgram/.env


  backend:
    image: ibonish/foodgram_backend
    restart: always
    volumes:
      - static_dir:/app/static/
      - media_dir:/app/media/
    env_file:
      - ../backend/foodgram/.env
    depends_on:
      - db


  nginx:
    image: nginx:1.23.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_dir:/var/html/static/
      - media_dir:/var/html/media/
    depends_on:
      - backend
      - frontend


volumes:
  static_dir:
  media_dir:
  postgres_data: