# Generated by Django 4.2.2 on 2023-07-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amountingridients',
            old_name='amount',
            new_name='amountingridients',
        ),
    ]
